stages:
  - deploy

cache:
  paths:
    - node_modules/

prod:
  stage: prod
  image: rastasheep/ubuntu-sshd
  before_script:
    - touch AWS_USPREQ.pem
    - echo "$DEPLOY_KEY" > AWS_USPREQ.pem
  script:
    - ssh -i "AWS_USPREQ.pem" ec2-user@ec2-18-218-147-236.us-east-2.compute.amazonaws.com "cd uspreq; git pull; npm run build; docker-compose down -v; docker-compose up"