stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  image: rastasheep/ubuntu-sshd
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/AWS_USPREQ.pem
    - chmod 600 ~/.ssh/AWS_USPREQ.pem
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/AWS_USPREQ.pem
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - ssh -i "~/.ssh/AWS_USPREQ.pem" ec2-user@$DEPLOY_SERVER "cd ~/uspreq/backend; git pull; sudo docker-compose down -v; sudo docker-compose up --build; sleep 20; cat ~/uspreq/backend/src/index.ts > ~/uspreq/backend/src/index.ts"