version: '3.7'

services:
  neo4j:
    image: neo4j:4.1.0
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - graph:/data

  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - neo4j

volumes:
  data:
  graph:
