version: '3.7'

services:
  neo4j:
    image: neo4j:4.1.0
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - graph:/data

  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: devboost_server
      POSTGRES_DB: server_database
    volumes:
      - data:/var/lib/postgresql/data
    depends_on:
      - neo4j

  server:
    build: .
    ports:
      - 80:3000
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: devboost_server
      POSTGRES_DB: server_database
      POSTGRES_HOST: database
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
      - neo4j

volumes:
  data:
  graph:
